repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # frozen: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: 77c3c6a34b2577d71083442326c60b8fd58926ec # frozen: v8.18.4
    hooks:
      - id: gitleaks

  - repo: https://github.com/executablebooks/mdformat
    rev: 08fba30538869a440b5059de90af03e3502e35fb # frozen: 0.7.17
    hooks:
      - id: mdformat

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: f295829140d25717bc79368d3f966fc1f67a824f # frozen: v0.41.0
    hooks:
      - id: markdownlint-fix-docker

  - repo: https://github.com/golangci/golangci-lint
    rev: c2e095c022a97360f7fff5d49fbc11f273be929a # frozen: v1.60.3
    hooks:
      - id: golangci-lint
