repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: 2ca41cc1372d1e939a6a879f18cdc19fc1cac1ce  # frozen: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/executablebooks/mdformat
    rev: 2d496dbc18e31b83a1596685347ffe0b6041daf0  # frozen: 1.0.0
    hooks:
      - id: mdformat

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 5b5dddc4fb0f83c3ea1fc5616fa63e115dce83e0  # frozen: v0.49.1
    hooks:
      - id: markdownlint-fix-docker

  - repo: https://github.com/golangci/golangci-lint
    rev: c4e8435b673b0c51918007429309bf9d3cbca904  # frozen: v2.13.2
    hooks:
      - id: golangci-lint
