name: "Update dependabot unsupported dependencies"

on:
  schedule:
    - cron: "5 0 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit:
    name: "Pre-commit Dependency Update"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: "Checkout Repository"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: "Setup Python"
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0

      - name: "Update .pre-commit-config.yml"
        run: |
          pip install pre-commit
          pre-commit autoupdate --freeze

      - name: "Create new pull-request"
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        if: always()
        with:
          branch: update/pre-commit-hooks
          title: "⬆️ pch: Update pre-commit hook versions"
          commit-message: "⬆️ pch: Update pre-commit hook versions"
          labels: "dependencies,pre-commit"
