name: "Update dependabot unsupported dependencies"

on:
  schedule:
    - cron: "5 0 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit:
    name: "Pre-commit Dependency Update"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: "Checkout Repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Setup Python"
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0

      - name: "Update .pre-commit-config.yml"
        run: |
          pip install pre-commit
          pre-commit autoupdate --freeze

      - name: "Create new pull-request"
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        if: always()
        with:
          branch: update/pre-commit-hooks
          title: "⬆️ pch: Update pre-commit hook versions"
          commit-message: "⬆️ pch: Update pre-commit hook versions"
          labels: "dependencies,pre-commit"
